import './globals.css'
import type { Metadata } from 'next'
import { Inter,DM_Sans,DM_Serif_Display } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client'

const inter = Inter({ subsets: ['latin'] })
const  dmsans=DM_Sans({weight:["400","500","700"],subsets:['latin'],variable:"--dm_sans"});
const dmserif=DM_Serif_Display({weight:["400"],subsets:['latin'],variable:'--dmserif'})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
      <body className={`${inter.className} ${dmsans.variable} ${dmserif.variable} font-body`}>
        {children}
        </body>
        </UserProvider>
    </html>
  )
}
